<?php
/**
 * Generated by framework installer - Mon, 12 Oct 2015 18:29:21 +0200
*/
    class Config
    {
	const BASEDNAME	= '/project';
	const DBHOST	= 'localhost';
	const DB	= 'openaccess';
	const DBUSER	= 'csc3123';
	const DBPW	= 'Harbinger13';
	const SITENAME	= 'project';
	const SITEURL	= 'http://www.webtechproject.co.uk';
	const SITENOREPLY	= 'admin@fdsiuf.com';
	const SYSADMIN	= 's.smolorz@ncl.ac.uk';
    }
?>